name: Tag Latest Release

description: |
  Pushes a tag for commits on master which change the 'version' field in the
  specified files

inputs:
  tagsAndFiles:
    description: |
      A string which on each line has a tag prefix and a path to a yaml or json
      file with a 'version' field separated by spaces.
    required: false
    default: |
      v package.yaml

  pushTags:
    description: |
      Push the tags as well as just create them
    required: false
    default: true

  token:
    description: GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)
    default: ${{ github.token }}

runs:
  using: composite
  steps:
  - run: |
      sudo pip3 install yq
    shell: bash

  - run: |
      sed 's/ \+/\t/;/^$/d' <<< "$INPUT_TAGSANDFILES" |
      while IFS=$'\t' read -r tagPrefix path; do
        ${{ github.action_path }}/../tag-latest-release.sh --package "$path" --tag-prefix "$tagPrefix"
      done
    shell: bash
    env:
      INPUT_TAGSANDFILES: ${{ inputs.tagsAndFiles }}

  - run: |
      if [ "$INPUT_PUSHTAGS" = true ]; then
        repo="https://${INPUT_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git push "$repo" --tags
      fi
    shell: bash
    env:
      INPUT_TOKEN: ${{ inputs.token }}
      INPUT_PUSHTAGS: ${{ inputs.pushTags }}
